name: controls_and_panels
author: Daniel Robinson
version: 0.0.0
description: controls and panels for developing a UI programmatically.
environment:
  sdk: any
dependencies:
  browser: any
dev_dependencies:
  unittest: any
